### PR TITLE
Red comments fixed, switched to noninteraction models

### PR DESCRIPTION
**Pull request by Jesse-Islam**
need to use IPA and fix lollipop plot.

### CODE REVIEW

**Comment by turgeonmaxime** [comment]
Thanks @Jesse-Islam for the pull request. But I'm a bit confused by your comment above:

> need to use IPA and fix lollipop plot.

Is this what the PR does, or what you wish it did? In other words, can I merge this into the `master` branch, or do you plan to add more commits?

**Comment by Jesse-Islam** [comment]
Yes! its more an update of what was done and what's still left

an issue though, its not building on travis (my personal fork) and im working on that.

**Comment by turgeonmaxime** [comment]
@Jesse-Islam can you clarify which "personal fork" does not build on Travis? Is it for this paper (`cbpaper`) or for the package (`casebase`)? 

- The `cbpaper` repo looks fine to me, every build was OK: https://hub.docker.com/r/sahirbhatnagar/cbpaper/builds

- I had a quick look at your fork of `casebase`, and the file `IPA.R` is problematic. In particular, on the first line you're importing `casebase`, which means that every time you run `library(casebase)`, it sources the file `IPA.R`, which runs `library(casebase)`, which sources `IPA.R`, etc. So you're stuck in an infinite loop.

**Comment by Jesse-Islam** [comment]
The problem was with cbpaper, but so long as it's working on your end
that's great! For casebase, I'm still in the testing phase of IPA, as there
is a disagreement between my repurposed code and the method in
riskRegression. This will become a proper function when I pull request it.

**Comment by turgeonmaxime** [comment]
As discussed this morning, I'll be merging this. The remaining changes to the regularized regression case study will be part of a future pull request.

**Pull request merged**
